# Constants related to Xapian search

# Values (like MarkLogic fields) are positionally-indexed
SEARCH_BOOK_ID = 0
SEARCH_BOOK_TITLE = 1
SEARCH_CHAPTER_ID = 2
SEARCH_CHAPTER_TITLE = 3
SEARCH_NAMESPACE = 4
SEARCH_AUTHOR_NAME = 5
SEARCH_LANGUAGE_VALUE = 6
SEARCH_CHAPTER_FILENAME = 7

DEFAULT_LANGUAGE_VALUE = 'english'
SORT_RELEVANCE = 0
SORT_ORDINAL = 1
RESULTS_PAGESIZE = 20

RESULT_ELEMENT = 'span'
RESULT_ELEMENT_CLASS = 'bw-match'
RESULT_WORD_BREAKS = 20

XHTML_NS = 'http://www.w3.org/1999/xhtml'
