application: book-worm
version: 1
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: library/static

- url: /view/.*
  script: main.py
  login: required

- url: /chapter/.*
  script: main.py
  login: required

- url: /css/.*
  script: main.py
  login: required

- url: /profile/.*
  script: main.py
  login: required

- url: /download/.*
  script: main.py
  login: required

- url: /admin/.*
  script: main.py
  login: admin

   
- url: /.*
  script: main.py

